name: haru

services:
  pub:
    image: haru/haru-os:ros1
    command: ["rostopic", "pub", "/hello", "std_msgs/String", "data: 'Hello from Docker'", "-r", "1"]
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
    network_mode: host
    devices:
      - /dev/snd
      - /dev/bus/usb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  echo:
    image: haru/haru-os:ros1
    command: ["rostopic", "echo", "/hello"]
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
    network_mode: host
    devices:
      - /dev/snd
      - /dev/bus/usb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
