name: haru-os

services:

  pub-root:
    image: haru/haru-os:ros2
    command: ["ros2", "topic", "pub", "/root", "std_msgs/msg/String", "{data: Hello from root}"]
    environment:
      - DISPLAY=${DISPLAY:-=:0}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  pub-user:
    image: haru/haru-os:ros2
    user: 1000:1000
    command: ["ros2", "topic", "pub", "/user", "std_msgs/msg/String", "{data: Hello from user}"]
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  echo-root:
    image: haru/haru-os:ros2
    command: ["ros2", "topic", "echo", "/user"]
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: on-failure

  echo-user:
    image: haru/haru-os:ros2
    user: 1000:1000
    command: ["ros2", "topic", "echo", "/root"]
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: on-failure
