name: haru-simulator

services:
  unity:
    image: haru/haru-simulator:ros1
    command: [ "/bin/bash", "-c", "roslaunch haru_unity unity_app_launcher.launch && tail -f /dev/null" ]
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
    network_mode: host
    devices:
      - /dev/snd
      - /dev/bus/usb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    runtime: nvidia
